language: go
go:
        - 1.8.x
        - 1.9.x

install:
        - mkdir -p $HOME/gopath/src/baliance.com/
        - ln -s $HOME/gopath/src/github.com/baliance/gooxml $HOME/gopath/src/github.com/qnfnypen/gooxml

script:
        - cd $HOME/gopath/src/github.com/qnfnypen/gooxml
        - ./build-examples.sh
        - go vet ./...
        - go test ./...
        - GOFMT=$(gofmt -d -s .) && echo $GOFMT && test -z "$GOFMT"

after_success:
        - ./test-coverage.sh
